services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@1
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/msmsql
  redis:
    image: redis:latest  
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
   redis-data:
   sql-data:

