services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@1
    ports:
      - "1433:1433"
